exclude: ".git"
default_stages: [commit]
fail_fast: true

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer

  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black

  - repo: https://github.com/timothycrosley/isort
    rev: 5.12.0
    hooks:
      - id: isort

  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args: ["--config=setup.cfg"]
        additional_dependencies: [flake8-isort]

  - repo: https://github.com/jazzband/pip-tools
    rev: 6.12.3
    hooks:
      - id: pip-compile
        name: pip-compile requirements/base.txt
        args: [--generate-hashes, requirements/base.in]
        files: ^requirements/base\.(in|txt)$
      - id: pip-compile
        name: pip-compile requirements/prod.txt
        args: [--generate-hashes, requirements/prod.in]
        files: ^requirements/prod\.(in|txt)$
      - id: pip-compile
        name: pip-compile requirements/dev.txt
        args: [--generate-hashes, requirements/dev.in]
        files: ^requirements/dev\.(in|txt)$
