files:
  - source: /client/locales/en/*.json
    translation: /client/locales/%two_letters_code%/%original_file_name%
  - source: /client/content/pages/en/*.md
    translation: /client/content/pages/%two_letters_code%/%original_file_name%
