version: "3.9"
services:
  fastapi:
    build:
      context: .
      dockerfile: ./compose/production/fastapi/Dockerfile
    depends_on:
      - postgres
    env_file:
      - ./.envs/.production/.postgres

  caddy:
    image: caddy:2.7.4
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    env_file:
      - ./.envs/.production/.caddy
    volumes:
      - ./compose/production/caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./site:/srv
      - caddy_data:/data
      - caddy_config:/config
    
  postgres:
    image: postgres:16
    volumes:
      - sni_postgres_data:/var/lib/postgresql/data
      - sni_postgres_data_backups:/backups
    env_file:
      - ./.envs/.production/.postgres

volumes:
  caddy_data:
  caddy_config:
  sni_postgres_data: {}
  sni_postgres_data_backups: {}
