version: '3'
services:
  flask:
    build:
      context: .
      dockerfile: ./compose/local/flask/Dockerfile
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
    env_file:
      - ./.envs/.local/.flask
    volumes:
      - .:/app:z
    ports:
      - "5000:5000"
