services:
  fastapi:
    build:
      context: .
      dockerfile: ./compose/local/fastapi/Dockerfile
    depends_on:
      - postgres
    volumes:
      - ./migrations:/app/migrations:z
    env_file:
      - ./.envs/.local/.fastapi
      - ./.envs/.local/.postgres
    develop:
      # Create a `watch` configuration to update the appl
      # https://docs.docker.com/compose/file-watch/#compose-watch-versus-bind-mounts
      watch:
        # Sync the working directory with the `/app` directory in the container
        - action: sync
          path: .
          target: /app
          # Exclude the project virtual environment — it could be for a
          # different platform in the container
          ignore:
            - "**/*.pyc"
            - "**/__pycache__"
            - ".venv/"

        # Rebuild the image on changes to the `pyproject.toml`
        - action: rebuild
          path: ./pyproject.toml
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true

  postgres:
    image: postgres:16
    volumes:
      - sni_local_postgres_data:/var/lib/postgresql/data
      - sni_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres
    ports:
      - "5234:5432"

volumes:
  sni_local_postgres_data: {}
  sni_local_postgres_data_backups: {}
