[project]
name = "sni"
version = "0.1.0"
description = "Advancing and preserving bitcoin knowledge"
requires-python = ">=3.12"
dependencies = [
    "alembic-postgresql-enum==1.7.0",
    "beautifulsoup4==4.13.4",
    "boto3==1.38.14",
    "fastapi[standard]==0.115.12",
    "feedgen==1.0.0",
    "markdown-it-py==3.0.0",
    "mdit-py-plugins==0.4.2",
    "psycopg[binary,pool]==3.2.9",
    "pydantic-settings==2.9.1",
    "pygments>=2.19.1",
    "pyyaml==6.0.2",
    "SQLAlchemy[asyncio,mypy]==2.0.40",
    "typer==0.15.3",
]

[tool.uv]
package = false
dev-dependencies = [
    "ruff==0.11.9",
    "types-beautifulsoup4==4.12.0.20250204",
    "types-PyYaml==6.0.12.20250402",
]

[tool.ruff]
lint.select = ["E", "F", "I"]
