[project]
name = "sni"
version = "0.1.0"
description = "Advancing and preserving bitcoin knowledge"
requires-python = ">=3.12"
dependencies = [
    "alembic-postgresql-enum==1.3.0",
    "beautifulsoup4==4.12.3",
    "boto3==1.35.17",
    "fastapi[standard]==0.114.1",
    "feedgen==1.0.0",
    "markdown-it-py==3.0.0",
    "mdit-py-plugins==0.4.2",
    "psycopg[binary,pool]==3.2.1",
    "pydantic-settings==2.5.2",
    "pyyaml==6.0.2",
    "SQLAlchemy[asyncio,mypy]==2.0.34",
    "typer==0.12.5",
]

[tool.uv]
package = false
dev-dependencies = [
    "ruff==0.6.4",
    "types-beautifulsoup4==4.12.0.20240907",
    "types-PyYaml==6.0.12.20240808",
]

[tool.ruff]
lint.select = ["E", "F", "I"]
