[project]
name = "sni"
version = "0.1.0"
description = "Advancing and preserving bitcoin knowledge"
requires-python = ">=3.12"
dependencies = [
    "alembic-postgresql-enum==1.4.0",
    "beautifulsoup4==4.12.3",
    "boto3==1.35.75",
    "fastapi[standard]==0.115.6",
    "feedgen==1.0.0",
    "markdown-it-py==3.0.0",
    "mdit-py-plugins==0.4.2",
    "psycopg[binary,pool]==3.2.3",
    "pydantic-settings==2.6.1",
    "pyyaml==6.0.2",
    "SQLAlchemy[asyncio,mypy]==2.0.36",
    "typer==0.15.1",
]

[tool.uv]
package = false
dev-dependencies = [
    "ruff==0.8.1",
    "types-beautifulsoup4==4.12.0.20241020",
    "types-PyYaml==6.0.12.20240917",
]

[tool.ruff]
lint.select = ["E", "F", "I"]
